--------------------------------------------------------------------------------
-- SERVICIOS_LAV (páginas APEX 6 y 7) — paquete CRUD + endpoints ORDS.
-- Ejecutar completo como el esquema de la app (WKSP_EVAMAR).
-- Requiere login.sql (paquete CC_AUTH).
--
-- PK id_servicio GENERATED BY DEFAULT AS IDENTITY (no se pasa en el INSERT).
-- Todas las columnas son NOT NULL:
--   descripcion    VARCHAR2(500)
--   estado         VARCHAR2(1)   -> 'A' activo / 'I' inactivo
--   precio         NUMBER
--   porc_comision  NUMBER
--
-- NOTA: el catálogo también se lee desde /servicios (ver servicios.sql), que
-- alimenta el selector del alta de lavados. Ese endpoint sigue existiendo; acá
-- se agregan las operaciones de escritura y el detalle.
--
-- === 1) PAQUETE PKG_CATALOGO_CLEANCAR ======================================
--------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE PKG_CATALOGO_CLEANCAR AS

  PROCEDURE LISTAR(p_token IN VARCHAR2);
  PROCEDURE OBTENER(p_token IN VARCHAR2, p_id_servicio IN NUMBER);
  PROCEDURE INSERTAR(
      p_token IN VARCHAR2, p_descripcion IN VARCHAR2, p_estado IN VARCHAR2,
      p_precio IN NUMBER, p_porc_comision IN NUMBER);
  PROCEDURE ACTUALIZAR(
      p_token IN VARCHAR2, p_id_servicio IN NUMBER, p_descripcion IN VARCHAR2,
      p_estado IN VARCHAR2, p_precio IN NUMBER, p_porc_comision IN NUMBER);
  PROCEDURE ELIMINAR(p_token IN VARCHAR2, p_id_servicio IN NUMBER);

END PKG_CATALOGO_CLEANCAR;
/

CREATE OR REPLACE PACKAGE BODY PKG_CATALOGO_CLEANCAR AS

  PROCEDURE p_error(p_status IN NUMBER, p_reason IN VARCHAR2, p_message IN VARCHAR2) IS
  BEGIN
    OWA_UTIL.STATUS_LINE(p_status, p_reason, FALSE);
    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', FALSE);
    APEX_JSON.WRITE('message', p_message);
    APEX_JSON.CLOSE_OBJECT;
  END p_error;

  FUNCTION f_usuario(p_token IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN CC_AUTH.VALIDAR_TOKEN(p_token);
  END f_usuario;

  --------------------------------------------------------------------------
  -- LISTAR
  --------------------------------------------------------------------------
  PROCEDURE LISTAR(p_token IN VARCHAR2) IS
    l_usuario VARCHAR2(255);
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.OPEN_ARRAY('data');
    FOR r IN (
        SELECT id_servicio, descripcion, estado, precio, porc_comision
          FROM servicios_lav
         ORDER BY descripcion
    ) LOOP
      APEX_JSON.OPEN_OBJECT;
      APEX_JSON.WRITE('id_servicio', r.id_servicio);
      APEX_JSON.WRITE('descripcion', r.descripcion);
      APEX_JSON.WRITE('estado', r.estado);
      APEX_JSON.WRITE('precio', r.precio);
      APEX_JSON.WRITE('porc_comision', r.porc_comision);
      APEX_JSON.CLOSE_OBJECT;
    END LOOP;
    APEX_JSON.CLOSE_ARRAY;
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
  END LISTAR;

  --------------------------------------------------------------------------
  -- OBTENER
  --------------------------------------------------------------------------
  PROCEDURE OBTENER(p_token IN VARCHAR2, p_id_servicio IN NUMBER) IS
    l_usuario VARCHAR2(255);
    l_row     servicios_lav%ROWTYPE;
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    BEGIN
      SELECT * INTO l_row
        FROM servicios_lav
       WHERE id_servicio = p_id_servicio;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        p_error(404, 'Not Found', 'Servicio no encontrado');
        RETURN;
    END;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.OPEN_OBJECT('data');
    APEX_JSON.WRITE('id_servicio', l_row.id_servicio);
    APEX_JSON.WRITE('descripcion', l_row.descripcion);
    APEX_JSON.WRITE('estado', l_row.estado);
    APEX_JSON.WRITE('precio', l_row.precio);
    APEX_JSON.WRITE('porc_comision', l_row.porc_comision);
    APEX_JSON.CLOSE_OBJECT;
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
  END OBTENER;

  --------------------------------------------------------------------------
  -- INSERTAR (id por IDENTITY)
  --------------------------------------------------------------------------
  PROCEDURE INSERTAR(
      p_token IN VARCHAR2, p_descripcion IN VARCHAR2, p_estado IN VARCHAR2,
      p_precio IN NUMBER, p_porc_comision IN NUMBER) IS
    l_usuario     VARCHAR2(255);
    l_id_servicio servicios_lav.id_servicio%TYPE;
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;

    IF p_descripcion IS NULL THEN
      p_error(400, 'Bad Request', 'La descripcion es obligatoria');
      RETURN;
    END IF;
    IF p_precio IS NULL THEN
      p_error(400, 'Bad Request', 'El precio es obligatorio');
      RETURN;
    END IF;

    -- estado y porc_comision son NOT NULL: si no vienen, valores por defecto.
    INSERT INTO servicios_lav (descripcion, estado, precio, porc_comision)
    VALUES (p_descripcion, NVL(p_estado, 'A'), p_precio, NVL(p_porc_comision, 0))
    RETURNING id_servicio INTO l_id_servicio;
    COMMIT;

    OWA_UTIL.STATUS_LINE(201, 'Created', FALSE);
    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.WRITE('message', 'Servicio creado');
    APEX_JSON.WRITE('id_servicio', l_id_servicio);
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
  END INSERTAR;

  --------------------------------------------------------------------------
  -- ACTUALIZAR
  --------------------------------------------------------------------------
  PROCEDURE ACTUALIZAR(
      p_token IN VARCHAR2, p_id_servicio IN NUMBER, p_descripcion IN VARCHAR2,
      p_estado IN VARCHAR2, p_precio IN NUMBER, p_porc_comision IN NUMBER) IS
    l_usuario VARCHAR2(255);
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;
    IF NOT CC_AUTH.ES_ADMIN(l_usuario) THEN
      p_error(403, 'Forbidden', 'No tenes permiso para modificar registros');
      RETURN;
    END IF;

    IF p_descripcion IS NULL THEN
      p_error(400, 'Bad Request', 'La descripcion es obligatoria');
      RETURN;
    END IF;
    IF p_precio IS NULL THEN
      p_error(400, 'Bad Request', 'El precio es obligatorio');
      RETURN;
    END IF;

    UPDATE servicios_lav
       SET descripcion   = p_descripcion,
           estado        = NVL(p_estado, 'A'),
           precio        = p_precio,
           porc_comision = NVL(p_porc_comision, 0)
     WHERE id_servicio = p_id_servicio;

    IF SQL%ROWCOUNT = 0 THEN
      ROLLBACK;
      p_error(404, 'Not Found', 'Servicio no encontrado');
      RETURN;
    END IF;
    COMMIT;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.WRITE('message', 'Servicio actualizado');
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
  END ACTUALIZAR;

  --------------------------------------------------------------------------
  -- ELIMINAR
  --------------------------------------------------------------------------
  PROCEDURE ELIMINAR(p_token IN VARCHAR2, p_id_servicio IN NUMBER) IS
    l_usuario VARCHAR2(255);
  BEGIN
    l_usuario := f_usuario(p_token);
    IF l_usuario IS NULL THEN
      p_error(401, 'Unauthorized', 'Token invalido o expirado');
      RETURN;
    END IF;
    IF NOT CC_AUTH.ES_ADMIN(l_usuario) THEN
      p_error(403, 'Forbidden', 'No tenes permiso para eliminar registros');
      RETURN;
    END IF;

    DELETE FROM servicios_lav WHERE id_servicio = p_id_servicio;

    IF SQL%ROWCOUNT = 0 THEN
      ROLLBACK;
      p_error(404, 'Not Found', 'Servicio no encontrado');
      RETURN;
    END IF;
    COMMIT;

    APEX_JSON.OPEN_OBJECT;
    APEX_JSON.WRITE('success', TRUE);
    APEX_JSON.WRITE('message', 'Servicio eliminado');
    APEX_JSON.CLOSE_OBJECT;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      IF SQLCODE = -2292 THEN
        p_error(409, 'Conflict',
                'No se puede eliminar: el servicio tiene lavados registrados');
      ELSE
        p_error(500, 'Internal Server Error', 'Error: ' || SQLERRM);
      END IF;
  END ELIMINAR;

END PKG_CATALOGO_CLEANCAR;
/

--------------------------------------------------------------------------------
-- === 2) ENDPOINTS ORDS =====================================================
--
--   GET    /api/catalogo-servicios       -> listar
--   GET    /api/catalogo-servicios/:id   -> obtener
--   POST   /api/catalogo-servicios       -> insertar
--   PUT    /api/catalogo-servicios/:id   -> actualizar
--   DELETE /api/catalogo-servicios/:id   -> eliminar
--
-- Se usa 'catalogo-servicios' y no 'servicios' porque /servicios ya está
-- tomado por el endpoint de solo lectura que alimenta el selector del alta.
--------------------------------------------------------------------------------

BEGIN
  BEGIN ORDS.DELETE_HANDLER('cleancar.api', 'catalogo-servicios', 'GET');        EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('cleancar.api', 'catalogo-servicios', 'POST');       EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('cleancar.api', 'catalogo-servicios/:id', 'GET');    EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('cleancar.api', 'catalogo-servicios/:id', 'PUT');    EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN ORDS.DELETE_HANDLER('cleancar.api', 'catalogo-servicios/:id', 'DELETE'); EXCEPTION WHEN OTHERS THEN NULL; END;

  ----------------------------------------------------------------------------
  -- /catalogo-servicios
  ----------------------------------------------------------------------------
  BEGIN
    ORDS.DEFINE_TEMPLATE(p_module_name => 'cleancar.api', p_pattern => 'catalogo-servicios',
        p_priority => 0, p_etag_type => 'HASH', p_comments => NULL);
  EXCEPTION WHEN OTHERS THEN NULL; END;

  ORDS.DEFINE_HANDLER(
      p_module_name => 'cleancar.api', p_pattern => 'catalogo-servicios', p_method => 'GET',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE l_token VARCHAR2(256); l_pos PLS_INTEGER;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    PKG_CATALOGO_CLEANCAR.LISTAR(p_token => l_token);
END;
~');
  ORDS.DEFINE_PARAMETER(p_module_name => 'cleancar.api', p_pattern => 'catalogo-servicios', p_method => 'GET',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ORDS.DEFINE_HANDLER(
      p_module_name => 'cleancar.api', p_pattern => 'catalogo-servicios', p_method => 'POST',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE l_token VARCHAR2(256); l_pos PLS_INTEGER;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    PKG_CATALOGO_CLEANCAR.INSERTAR(
        p_token         => l_token,
        p_descripcion   => :descripcion,
        p_estado        => :estado,
        p_precio        => TO_NUMBER(:precio),
        p_porc_comision => TO_NUMBER(:porc_comision));
END;
~');
  ORDS.DEFINE_PARAMETER(p_module_name => 'cleancar.api', p_pattern => 'catalogo-servicios', p_method => 'POST',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ----------------------------------------------------------------------------
  -- /catalogo-servicios/:id
  ----------------------------------------------------------------------------
  BEGIN
    ORDS.DEFINE_TEMPLATE(p_module_name => 'cleancar.api', p_pattern => 'catalogo-servicios/:id',
        p_priority => 0, p_etag_type => 'HASH', p_comments => NULL);
  EXCEPTION WHEN OTHERS THEN NULL; END;

  ORDS.DEFINE_HANDLER(
      p_module_name => 'cleancar.api', p_pattern => 'catalogo-servicios/:id', p_method => 'GET',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE l_token VARCHAR2(256); l_pos PLS_INTEGER;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    PKG_CATALOGO_CLEANCAR.OBTENER(p_token => l_token, p_id_servicio => TO_NUMBER(:id));
END;
~');
  ORDS.DEFINE_PARAMETER(p_module_name => 'cleancar.api', p_pattern => 'catalogo-servicios/:id', p_method => 'GET',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ORDS.DEFINE_HANDLER(
      p_module_name => 'cleancar.api', p_pattern => 'catalogo-servicios/:id', p_method => 'PUT',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE l_token VARCHAR2(256); l_pos PLS_INTEGER;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    PKG_CATALOGO_CLEANCAR.ACTUALIZAR(
        p_token         => l_token,
        p_id_servicio   => TO_NUMBER(:id),
        p_descripcion   => :descripcion,
        p_estado        => :estado,
        p_precio        => TO_NUMBER(:precio),
        p_porc_comision => TO_NUMBER(:porc_comision));
END;
~');
  ORDS.DEFINE_PARAMETER(p_module_name => 'cleancar.api', p_pattern => 'catalogo-servicios/:id', p_method => 'PUT',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ORDS.DEFINE_HANDLER(
      p_module_name => 'cleancar.api', p_pattern => 'catalogo-servicios/:id', p_method => 'DELETE',
      p_source_type => 'plsql/block',
      p_source      => q'~
DECLARE l_token VARCHAR2(256); l_pos PLS_INTEGER;
BEGIN
    OWA_UTIL.MIME_HEADER('application/json', FALSE);
    OWA_UTIL.HTTP_HEADER_CLOSE;
    l_token := :authorization;
    IF l_token IS NOT NULL THEN
        l_pos := INSTR(UPPER(l_token), 'BEARER ');
        IF l_pos > 0 THEN l_token := TRIM(SUBSTR(l_token, l_pos + 7)); END IF;
    END IF;
    PKG_CATALOGO_CLEANCAR.ELIMINAR(p_token => l_token, p_id_servicio => TO_NUMBER(:id));
END;
~');
  ORDS.DEFINE_PARAMETER(p_module_name => 'cleancar.api', p_pattern => 'catalogo-servicios/:id', p_method => 'DELETE',
      p_name => 'Authorization', p_bind_variable_name => 'authorization',
      p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/

--------------------------------------------------------------------------------
-- === 3) CORS ===============================================================
--------------------------------------------------------------------------------
BEGIN
  ORDS.SET_MODULE_ORIGINS_ALLOWED(
    p_module_name     => 'cleancar.api',
    p_origins_allowed => 'https://josegalvez1985.github.io,http://localhost:8080,http://192.168.100.16:8080'
  );
  COMMIT;
END;
/
