/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VentasRouteImport } from './routes/ventas'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as HomeRouteImport } from './routes/home'
import { Route as BoxesRouteImport } from './routes/boxes'
import { Route as IndexRouteImport } from './routes/index'

const VentasRoute = VentasRouteImport.update({
  id: '/ventas',
  path: '/ventas',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxesRoute = BoxesRouteImport.update({
  id: '/boxes',
  path: '/boxes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boxes': typeof BoxesRoute
  '/home': typeof HomeRoute
  '/servicios': typeof ServiciosRoute
  '/ventas': typeof VentasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boxes': typeof BoxesRoute
  '/home': typeof HomeRoute
  '/servicios': typeof ServiciosRoute
  '/ventas': typeof VentasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boxes': typeof BoxesRoute
  '/home': typeof HomeRoute
  '/servicios': typeof ServiciosRoute
  '/ventas': typeof VentasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/boxes' | '/home' | '/servicios' | '/ventas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/boxes' | '/home' | '/servicios' | '/ventas'
  id: '__root__' | '/' | '/boxes' | '/home' | '/servicios' | '/ventas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoxesRoute: typeof BoxesRoute
  HomeRoute: typeof HomeRoute
  ServiciosRoute: typeof ServiciosRoute
  VentasRoute: typeof VentasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ventas': {
      id: '/ventas'
      path: '/ventas'
      fullPath: '/ventas'
      preLoaderRoute: typeof VentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boxes': {
      id: '/boxes'
      path: '/boxes'
      fullPath: '/boxes'
      preLoaderRoute: typeof BoxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoxesRoute: BoxesRoute,
  HomeRoute: HomeRoute,
  ServiciosRoute: ServiciosRoute,
  VentasRoute: VentasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
